schema_version: "1.0"

tracks:
  - id: backlog
    label: track/backlog
    description: Default backlog

labels:
  - name: phase-3.4
    description: Phase 3.4 – Marketplace Readiness
    color: "D93F0B"

milestones:
  - title: "Phase 3.4 – Marketplace Readiness"

enforcement:
  exclusivity:
    phase:
      mode: enforce
      strategy: highest

  phase_milestones:
    phase-3.4: "Phase 3.4 – Marketplace Readiness"
